server:
  port: 8084

spring:
  application:
    name: messaging-service
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:}
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
